### ISSUE TITLE
[4] Search APIs for artist albums and add them to the DB

### ISSUE THREAD

**Issue by JWLD** [JWLD/soundtracks-react#15]
- [ ] Create dev search route / component / view (#16)
- [ ] Search API for an artist and list top n results (#17)
- [ ] Search API for all albums by a particular artist and render as a list (#18)
- [ ] Edit album info and select all the albums to be added to the DB (#19)
- [ ] Query Spotify API for link to album artwork (#20)
- [ ] DB query to add finalised info to DB (#21)
