### ISSUE TITLE
[1] Search for artist

### ISSUE THREAD

**Issue by JWLD** [JWLD/soundtracks-react#5]
#4 

- [x] Create search bar component (#8)
- [x] Write DB query to get artists (#9)
- [x] Render list of artists (#10)

**As a user interested in a composer**
> I want to be able to search for an artist

> So that I can choose an artist featured on the website
